// The shared error taxonomy (plan/23-SPEC-errors.md). Codes are stable identifiers: adding one is
// fine, renaming one is a breaking change.

export type VadumErrorCode =
  | 'WIRE_VERSION_UNSUPPORTED'
  | 'WIRE_RESERVED_FLAG_SET'
  | 'WIRE_LENGTH_MISMATCH'
  | 'WIRE_UNKNOWN_TYPE'
  | 'WIRE_UNEXPECTED_TYPE'
  | 'WIRE_FLAGS_MISMATCH'
  | 'WIRE_STATIC_CONSTRAINT'
  | 'WIRE_BASE45_INVALID'
  | 'WIRE_FLAG_NOT_ALLOWED_FOR_TYPE'
  | 'WIRE_FEE_PAYER_SEPARATE_UNSUPPORTED'
  | 'WIRE_FEE_PAYER_IS_PAYER'
  | 'WIRE_DUPLICATE_AUTH'
  | 'MINT_UNKNOWN'
  | 'MINT_INCOMPATIBLE'
  | 'MINT_DECIMALS_MISMATCH'
  | 'MINT_TOKEN_PROGRAM_MISMATCH'
  | 'MINT_RECORD_STALE'
  | 'CANON_INSTRUCTION_NOT_ALLOWED'
  | 'CANON_ACCOUNT_MISMATCH'
  | 'CANON_AMOUNT_MISMATCH'
  | 'CANON_DESTINATION_MISMATCH'
  | 'CANON_INSTRUCTION_ORDER'
  | 'SIG_INVALID'
  | 'SIG_LENGTH'
  | 'SIG_FEE_PAYER_MISSING'
  | 'NONCE_INDEX_OUT_OF_RANGE'
  | 'NONCE_ALREADY_SPENT'
  | 'NONCE_LEDGER_MISSING'
  | 'NONCE_POOL_EXHAUSTED'
  | 'NONCE_POOL_UNDERFUNDED'
  | 'NONCE_DESYNC'
  | 'NONCE_RETURN_UNTRUSTED'
  | 'NONCE_ACCOUNT_CLOSED'
  | 'LIMIT_RECEIPT_CAP'
  | 'LIMIT_QUEUE_EXPOSURE'
  | 'LIMIT_FAILED_SENDS'
  | 'LIMIT_SEND_WINDOW_EXPIRED'
  | 'LIMIT_PRECHECK_REQUIRED'
  | 'LIMIT_PAYER_ALLOWANCE'
  | 'SUBMIT_NONCE_STALE'
  | 'SUBMIT_NONCE_ABSENT'
  | 'SUBMIT_EXECUTION_FAILED'
  | 'SUBMIT_ALREADY_PROCESSED'
  | 'SUBMIT_BLOCKHASH_EXPIRED'
  | 'SUBMIT_RPC_UNAVAILABLE'
  | 'INTERNAL_NOT_IMPLEMENTED'
  | 'INTERNAL_NOT_APPLICABLE';

/** Every code, for exhaustive copy maps (42-STREAM-C C7) and tests. */
export const VADUM_ERROR_CODES = [
  'WIRE_VERSION_UNSUPPORTED',
  'WIRE_RESERVED_FLAG_SET',
  'WIRE_LENGTH_MISMATCH',
  'WIRE_UNKNOWN_TYPE',
  'WIRE_UNEXPECTED_TYPE',
  'WIRE_FLAGS_MISMATCH',
  'WIRE_STATIC_CONSTRAINT',
  'WIRE_BASE45_INVALID',
  'WIRE_FLAG_NOT_ALLOWED_FOR_TYPE',
  'WIRE_FEE_PAYER_SEPARATE_UNSUPPORTED',
  'WIRE_FEE_PAYER_IS_PAYER',
  'WIRE_DUPLICATE_AUTH',
  'MINT_UNKNOWN',
  'MINT_INCOMPATIBLE',
  'MINT_DECIMALS_MISMATCH',
  'MINT_TOKEN_PROGRAM_MISMATCH',
  'MINT_RECORD_STALE',
  'CANON_INSTRUCTION_NOT_ALLOWED',
  'CANON_ACCOUNT_MISMATCH',
  'CANON_AMOUNT_MISMATCH',
  'CANON_DESTINATION_MISMATCH',
  'CANON_INSTRUCTION_ORDER',
  'SIG_INVALID',
  'SIG_LENGTH',
  'SIG_FEE_PAYER_MISSING',
  'NONCE_INDEX_OUT_OF_RANGE',
  'NONCE_ALREADY_SPENT',
  'NONCE_LEDGER_MISSING',
  'NONCE_POOL_EXHAUSTED',
  'NONCE_POOL_UNDERFUNDED',
  'NONCE_DESYNC',
  'NONCE_RETURN_UNTRUSTED',
  'NONCE_ACCOUNT_CLOSED',
  'LIMIT_RECEIPT_CAP',
  'LIMIT_QUEUE_EXPOSURE',
  'LIMIT_FAILED_SENDS',
  'LIMIT_SEND_WINDOW_EXPIRED',
  'LIMIT_PRECHECK_REQUIRED',
  'LIMIT_PAYER_ALLOWANCE',
  'SUBMIT_NONCE_STALE',
  'SUBMIT_NONCE_ABSENT',
  'SUBMIT_EXECUTION_FAILED',
  'SUBMIT_ALREADY_PROCESSED',
  'SUBMIT_BLOCKHASH_EXPIRED',
  'SUBMIT_RPC_UNAVAILABLE',
  'INTERNAL_NOT_IMPLEMENTED',
  'INTERNAL_NOT_APPLICABLE',
] as const satisfies readonly VadumErrorCode[];

const showDetail = (detail: Readonly<Record<string, unknown>>): string =>
  JSON.stringify(detail, (_key, value: unknown) => (typeof value === 'bigint' ? value.toString() : value));

export class VadumError extends Error {
  readonly code: VadumErrorCode;
  readonly detail?: Readonly<Record<string, unknown>>;

  constructor(code: VadumErrorCode, detail?: Readonly<Record<string, unknown>>) {
    super(detail === undefined ? code : `${code} ${showDetail(detail)}`);
    this.name = 'VadumError';
    this.code = code;
    if (detail !== undefined) this.detail = detail;
  }
}
